spring.application.name=individual

# server.port=8080

#Coneção com Bando:
spring.datasource.url=jdbc:postgresql://localhost:5432/aula03
spring.datasource.username=postgres
spring.datasource.password=v22457752

#DLL - como hibernate trata a estrutura do banco 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# SQL no Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect